###
GET https://web.lite24.net/api/post/chat?player=Mooner510&message=저기요
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=뭐요
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=왜그래요
###
GET https://web.lite24.net/api/post/chat?player=Mooner510&message=세미나실 가실래요
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=??
###
GET https://web.lite24.net/api/post/chat?player=Mooner510&message=세미나실이요
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=뭐하자는거지
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=어머
###
GET https://web.lite24.net/api/post/chat?player=Mooner510&message=가면 아이스크림이 있을거에요.
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=아이스크림이 왜있어요
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=ㄷㄷ
###
GET https://web.lite24.net/api/post/chat?player=Mooner510&message=체육쌤도 있을거에요.
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=아잇
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=이상한 소리하지마요
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=왜이래요
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=ㅑ궈래ㅑㅈㄷ후ㅐㅔ가리느아ㅐㄱㄷ어ㅏ
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=ㄷ갸러ㅗㅜ처ㅏㅑㅇ내ㅏㅓ두거ㅏㅑㄹ
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=더ㅜㅍ럴
###
GET https://web.lite24.net/api/post/chat?player=pswrbook715&message=댜개라ㅓㅍ차
###
GET https://web.lite24.net/api/post/chat?player=Mooner510&message=어머 안되겠네요